# Form implementation generated from reading ui file 'UI/Main Window.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import (QApplication, QMainWindow, QPushButton, 
                            QFileDialog, QVBoxLayout, QWidget, QLabel)


class Ui_MainWindow(QMainWindow):

    def __init__(self):
        """Initialize the main window and set up the UI components."""
        super().__init__()
        self.file_name = ""

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(367, 222)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.formLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(12, 124, 346, 55))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.formLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.Analyze = QtWidgets.QPushButton(parent=self.formLayoutWidget)
        self.Analyze.setObjectName("Analyze")
        self.gridLayout.addWidget(self.Analyze, 0, 3, 1, 1)
        self.save_data_button = QtWidgets.QPushButton(parent=self.formLayoutWidget)
        self.save_data_button.setObjectName("save_data_button")
        self.gridLayout.addWidget(self.save_data_button, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 1, 1, 2)
        self.formLayoutWidget_2 = QtWidgets.QWidget(parent=self.centralwidget)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(193, 42, 170, 60))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")


        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_3 = QtWidgets.QLabel(parent=self.formLayoutWidget_2)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_3)
        self.z_line_edit = QtWidgets.QLineEdit(parent=self.formLayoutWidget_2)
        self.z_line_edit.setObjectName("z_line_edit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.z_line_edit)
        self.label_2 = QtWidgets.QLabel(parent=self.formLayoutWidget_2)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_2)
        self.w_line_edit = QtWidgets.QLineEdit(parent=self.formLayoutWidget_2)
        self.w_line_edit.setObjectName("w_line_edit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.w_line_edit)
        self.Output = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.Output.setGeometry(QtCore.QRect(5, 41, 181, 60))
        self.Output.setObjectName("Output")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(parent=self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(7, 0, 350, 40))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.variable_type_combo = QtWidgets.QComboBox(parent=self.horizontalLayoutWidget_2)
        self.variable_type_combo.setObjectName("variable_type_combo")
        self.variable_type_combo.setPlaceholderText("Random Variable Type")
        self.variable_type_combo.addItem("")
        self.variable_type_combo.addItem("")
        self.variable_type_combo.addItem("")
        self.horizontalLayout_2.addWidget(self.variable_type_combo)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(parent=self.horizontalLayoutWidget_2)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.t_value = QtWidgets.QDoubleSpinBox(parent=self.horizontalLayoutWidget_2)
        self.t_value.setObjectName("t_value")
        self.horizontalLayout.addWidget(self.t_value)
        self.open_file_button = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_2)
        self.open_file_button.setObjectName("open_file_button")
        self.horizontalLayout.addWidget(self.open_file_button)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 367, 19))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        elements = [self.formLayoutWidget_2, self.t_value]
        self.disable_elements(elements)
        

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Analyze.setText(_translate("MainWindow", "Analyze"))
        self.save_data_button.setText(_translate("MainWindow", "Save Data"))
        self.label_3.setText(_translate("MainWindow", "Z"))
        self.label_2.setText(_translate("MainWindow", "W"))
        self.variable_type_combo.setItemText(0, _translate("MainWindow", "Single Random Variable"))
        self.variable_type_combo.setItemText(1, _translate("MainWindow", "Joint Random Variable"))
        self.variable_type_combo.setItemText(2, _translate("MainWindow", "Function of Random Variable"))
        self.label.setText(_translate("MainWindow", "t"))
        self.open_file_button.setText(_translate("MainWindow", "Open file"))
        self.open_file_button.clicked.connect(self.open_file_dialog)



    def disable_elements(self, elements):
        """takes a list of elements and disables them all"""
        for element in elements:
            element.setStyleSheet("""
                QLabel:disabled { color: #666666; }
            """)
            element.setEnabled(False)

    def open_file_dialog(self):
        """Open the file dialog and handle file selection."""
        # Show the file dialog and get the selected file
        file_name, _ = QFileDialog.getOpenFileName(
            self,                   # Parent widget
            "Select a File",        # Dialog title
            "",                     # Starting directory (empty for default)
            "All Files (*)"         # File filter
        )
          
        if file_name:
            self.file_name = file_name

    


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
